"""nambah deskripsi

Revision ID: 7293ae36c13c
Revises: 75a4968b55e9
Create Date: 2020-05-16 21:59:03.767193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7293ae36c13c'
down_revision = '75a4968b55e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_produk', sa.Column('deskripsi', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_produk', 'deskripsi')
    # ### end Alembic commands ###
