"""empty message

Revision ID: 75a4968b55e9
Revises: 
Create Date: 2020-05-16 10:55:14.500163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a4968b55e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_produk', sa.Column('gambar', sa.String(length=255), nullable=True))
    op.add_column('table_produk', sa.Column('gambar1', sa.String(length=255), nullable=True))
    op.add_column('table_produk', sa.Column('gambar2', sa.String(length=255), nullable=True))
    op.add_column('table_produk', sa.Column('gambar3', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_produk', 'gambar3')
    op.drop_column('table_produk', 'gambar2')
    op.drop_column('table_produk', 'gambar1')
    op.drop_column('table_produk', 'gambar')
    # ### end Alembic commands ###
